version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
    - "backend-related"

  - package-ecosystem: "pnpm"
    directory: "/src/AniTracker.Frontend/src"
    schedule:
      interval: "weekly"
    labels:
      - "frontend-related"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
    labels:
      - "ci-related"
